services:
  # Serviço do Frontend (HTML/CSS/JS)
  frontend:
    image: nginx:alpine
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: always
    environment:
      - SERVER_PORT=${SERVER_PORT}
      - NGINX_ENVSUBST_FILTER=SERVER_PORT
    ports:
      - '${APP_PORT}:80'
    depends_on:
      - backend

  # Serviço do Backend (Node.js)
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    restart: always
    volumes:
      - dados-pedidos:/app/backend/data
    env_file:
      - ./.env
    expose:
      - ${SERVER_PORT}

volumes:
  dados-pedidos:
